filters:
  - label: âš™ï¸ feat
    regexs:
      - /feat/i
    events: [issues, pull_request]
    targets: [title]
  - label: ğŸ› ï¸ fix
    regexs:
      - /fix/i
    events: [issues, pull_request]
    targets: [title]
  - label: ğŸ”¨ refactor
    regexs:
      - /refactor/i
    events: [issues, pull_request]
    targets: [title]
  - label: ğŸš€ deploy
    regexs:
      - /deploy/i
    events: [issues, pull_request]
    targets: [title]
